In [4]:
import numpy as np
# list1 = [1,2,3,4]
# oneArray = np.array(list1)
# print(type(oneArray))
# print(oneArray)

# # 创建数组的多种形式
# # 1. 直接传入列表的方式
# t1 = np.array([1,2,3])
# print(t1)
# print(type(t1))
t1 =  np.arange(9).reshape(3,3)
print(t1)
print(t1.sum(axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 3 12 21]
