In [1]:
import random
import time
import numpy as np
a = []
for i in range(1000000):
    a.append(random.random())
    
t1 = time.time()#当前时间
sum1=sum(a)#原生list计算时间
t2=time.time()#当前时间

b=np.array(a)
t4=time.time()
sum3=np.sum(b)#numpy计算的时间
t5=time.time()
print(t2-t1, t5-t4)

0.023935317993164062 0.0019948482513427734


In [1]:
import numpy as np
list1 = [1,2,3,4]
oneArray = np.array(list1)
print(type(oneArray))
print(oneArray)

# 创建数组的多种形式
# 1. 直接传入列表的方式
t1 = np.array([1,2,3])
print(t1)
print(type(t1))
t1 = np.arange(0,10,2)
print(t1)

<class 'numpy.ndarray'>
[1 2 3 4]
[1 2 3]
<class 'numpy.ndarray'>
[0 2 4 6 8]


In [9]:
import numpy as np
list2 = [[1,2],[3,4],[5,6]]
print(list2)


twoArray = np.array(list2)
print(twoArray)
#
print(twoArray.ndim)
#形状 几行几列 
print(twoArray.shape) # shape[0] * shape[1]
#尺寸
print(twoArray.size)



[[1, 2], [3, 4], [5, 6]]
[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)
6


In [7]:
four = np.array([[1,2,3],[4,5,6]]) 
print(four,four.shape)
# 修改的是原有的
#在原有数据上修改
# four.shape = (3,2)
# print(four)
#改变形状返回一个新的数据
arr = four.reshape(3,2)
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [8]:
# 将多维变成一维数组
five = four.reshape((6,),order='C')
print(five)
# 默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开
six = four.flatten(order='F')

print(six)

[1 2 3 4 5 6]


In [19]:
# 将数组转成list
a= np.array([9, 12, 88, 14, 25])
list_a = a.tolist()
print(list_a)
print(type(list_a))

[9, 12, 88, 14, 25]
<class 'list'>


In [3]:
f = np.array([1,2,3,4,5], dtype = np.int16)
# 返回数组中每个元素的字节单位长度
print(f.itemsize)
# 获取数据类型
print(f.dtype)

# 调整数据类型
f1 = f.astype(np.int64)
print(f1.dtype)

# 拓展随机生成小数
# 使用python语法，保留两位
print(round(random.random(),2))#0.6情况,课下扩展:查询官方文档round(random.random(),2) 

arr = np.array([random.random() for i in range(10)])
# 取小数点后两位
print(np.round(arr,2))

2
int16
int64
0.26
[0.33 0.47 0.58 0.55 0.46 0.24 0.13 0.35 0.2  0.25]


In [4]:
#数组与数进行计算 数组当中每一位数字都与对应数字进行计算
t1 = np.arange(24).reshape((6,4))
print(t1)
print(t1+2)
# print(t1*2)
# print(t1/2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


In [17]:
#同种形状的数组(对应位置进行计算操作)
t1 = np.arange(24).reshape((6,4))

print(t1.shape)
t2 = np.arange(100,124).reshape((6,4))
print(t2)

print(t1+t2)
# print(t1*t2)

(6, 4)
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]


In [6]:
#不同形状数组不能同时进行计算
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(18).reshape((3,6))
print(t1)
print(t2)
print(t1-t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


ValueError: operands could not be broadcast together with shapes (4,6) (3,6) 

In [10]:
#行数相同的情况下,可以进行计算(一维数组)
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(0,6)
#t2 = np.arange(6).reshape((1,6))
print(t1,t2)

print(t1-t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] [0 1 2 3 4 5]
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]


In [34]:
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(4).reshape((4,1)) # t2 1维数组 2维
print(t1,t2)
print(t1-t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] [[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


In [11]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
#计算的结果是一维数组
#根据0轴进行计算,按照列进行计算
print(np.sum(a,axis=0)) # [5 7 9]
#根据1轴进行计算,每一行进行计算
print(np.sum(a,axis = 1)) # [ 6 15]

print(np.sum(a))# 计算所有的值的和

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]
21


In [23]:
a = np.arange(9).reshape((3,3))
print(a)
print('-----------------------------')
print(a.ndim)
print(type(a))
print(a.shape)
print('-----------------------------')
b = np.sum(a, axis=1)
print(b)
c = np.sum(a, axis=0)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
-----------------------------
2
<class 'numpy.ndarray'>
(3, 3)
-----------------------------
[ 3 12 21]
[ 9 12 15]


In [27]:
a = np.arange(27).reshape((3,3,3))
print(a)
print('-----------------------------')
print(a.ndim)
print(type(a))
print(a.shape)
print('-----------------------------')
#计算的结果是一个二维数组
print('----------axis=2--------------')
d = np.sum(a, axis=2)
print(d)
print('----------axis=1-------------')
b = np.sum(a, axis=1)
print(b)
print('-----------axis=0--------------')
c = np.sum(a, axis=0)
print(c)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
-----------------------------
3
<class 'numpy.ndarray'>
(3, 3, 3)
-----------------------------
----------axis=2--------------
[[ 3 12 21]
 [30 39 48]
 [57 66 75]]
----------axis=1-------------
[[ 9 12 15]
 [36 39 42]
 [63 66 69]]
-----------axis=0--------------
[[27 30 33]
 [36 39 42]
 [45 48 51]]


In [42]:
#数据预处理  ------ 网上 sql  excle 不完成性,异常值
import numpy as np 
a = np.arange(10)
print(a)
#冒号切
print(a[2:7:2])
#取单个数据
print(a[4],a)
print(a[2:])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
4 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [48]:
import numpy as np
t1 = np.arange(24).reshape(4,6)
print(t1)

#取出第一行
print(t1[0])
#取连续多行
print(t1[1:])
#取1到3行
print(t1[1:3])
print('取不连续多行：')
#不连续多行
print(t1[[0,2]])
print(t1[[0,2],:]) #切片[[行,行],列[切片]]
print('切列')
print(t1[:,1])
print(t1[:,1:]) 
#[[行行行],[列列列]]
print('[行行行],[列列列]]')
print(t1[[0,1,1],[0,1,3]])
#无论行还是列,索引下标,从0开始



[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[0 1 2 3 4 5]
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
取不连续多行：
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]]
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]]
切列
[ 1  7 13 19]
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
[行行行],[列列列]]
[0 7 9]


In [52]:
t = np.arange(24).reshape(4,6)
print(t)
#单个数字赋值
t[[0,1],[1,2]]=0
print(t)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  0  2  3  4  5]
 [ 6  7  0  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [53]:
# 修改某一列的值
t[:,1]=0

# 修改连续多行
t[1:3,:]=0

# 修改连续多列
t[:,1:4]=0

# 修改多行多列，取第二行到第四行，第三列到第五列
t[1:4,2:5]=0
print(t)
#需求:如果数据大于10 全部变成0 
print(t<10)
t[t<10]=0
print(t)
#如果 大于2 并且小于6 变0 
#and or not 
t[(t>2) & (t<6)]=0
print(t)


[[ 0  0  0  0  4  5]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [18  0  0  0  0 23]]
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [False  True  True  True  True False]]
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [18  0  0  0  0 23]]
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [18  0  0  0  0 23]]


In [73]:
score = np.array([89,88,100,101,102,103,103,103]) 
#去除最高分的平均值
#取出数组最高分
largest = score.max()
print(largest)
print(score[score<largest].mean())
#课下练习: 多个最大值的去除,如果来计算

103
96.0


In [74]:
# 拓展
# 三目运算（ np.where(condition, x, y)满足条件(condition)，输出x，不满足输出y。)）
score = np.array([[80,88],[82,81],[75,81]])
result = np.where(score>80,True,False)
print(result)

[[False  True]
 [ True  True]
 [False  True]]


In [55]:
#nan 
# print(np.nan)
# print(type(np.nan))
# --判断数组中为nan的个数(注意：float类型的数据才能赋值nan)
t = np.arange(24,dtype=float).reshape(4,6)
# print(t)
t[3,4]=np.nan # nan与任意数字计算结果都是nan
print(t)
#验证所有数据与nan计算都为nan
print(np.sum(t[:,4]))
#判断数组中有没有nan
print(np.isnan(t))
#nan!=nan不等nan
#处理nan的方法.根据不同的需求:干掉nan 将nan填充为平均值 ,众数,中位数 
print(t!=t)
#查看一下,当前数组里面有多少个nan
print(np.count_nonzero(t!=t))


[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. nan 23.]]
nan
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False  True False]]
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False  True False]]
1


In [60]:
t = np.arange(24).reshape(4,6).astype('float')
t = np.arange(24).reshape(4,6).astype('float') 
# 将数组中的一部分替换nan
t[1,3:] = np.nan
print(t)
print('----------------------------------')
# 遍历每一列，然后判断每一列是否有nan
for i in range(t.shape[1]):
    #获取当前列数据
    temp_col = t[:,i]
    print(i,'temp_col:')
    print(temp_col)
    # 判断当前列的数据中是否含有nan
    nan_num = np.count_nonzero(temp_col != temp_col) 
    print('nan_num:',nan_num)
    
    if nan_num != 0: # 条件成立说明含有nan

        # 将这一列不为nan的数据拿出来
        temp_col_not_nan = temp_col[temp_col==temp_col]

        # 将nan替换成这一列的平均值
        temp_col[np.isnan(temp_col)] = np.mean(temp_col_not_nan)

print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
----------------------------------
0 temp_col:
[ 0.  6. 12. 18.]
nan_num: 0
1 temp_col:
[ 1.  7. 13. 19.]
nan_num: 0
2 temp_col:
[ 2.  8. 14. 20.]
nan_num: 0
3 temp_col:
[ 3. nan 15. 21.]
nan_num: 1
4 temp_col:
[ 4. nan 16. 22.]
nan_num: 1
5 temp_col:
[ 5. nan 17. 23.]
nan_num: 1
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. 13. 14. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


In [95]:
#对换数组的维度

a = np.arange(12).reshape(3,4)
 
print ('原数组：')
print (a )
print ('\n')
 
print ('对换数组：')
print (np.transpose(a))




原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [61]:
a = np.array([[1,2,3],[4,5,6]])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('向数组添加元素：')
print (np.append(a, [7,8,9]))
print ('\n')
 
print ('沿轴 0 添加元素：')
print (np.append(a, [[7,8,9]],axis = 0))
print ('\n')
 
print ('沿轴 1 添加元素：')
print (np.append(a, [[5,5,5],[7,8,9]],axis = 1))

第一个数组：
[[1 2 3]
 [4 5 6]]


向数组添加元素：
[1 2 3 4 5 6 7 8 9]


沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [62]:
a = np.arange(12).reshape(3,4)
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('未传递 Axis 参数。 在删除之前输入数组会被展开。')
print (np.delete(a,5))
print ('\n')
 
# print ('删除每一行中的第二列：')
print (np.delete(a,1,axis = 1))
print ('\n')

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


未传递 Axis 参数。 在删除之前输入数组会被展开。
[ 0  1  2  3  4  6  7  8  9 10 11]


[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]




In [66]:
a = np.array([5,2,6,2,7,5,6,8,2,9])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('第一个数组的去重值：')
u = np.unique(a)
print (u)
print ('\n')
 
# print ('去重数组的索引数组：')
indices = np.unique(a, return_index = True)
print (indices)
print ('\n')

u,indices = np.unique(a, return_index = True)
print(u)
print (indices)
print ('\n')

第一个数组：
[5 2 6 2 7 5 6 8 2 9]


第一个数组的去重值：
[2 5 6 7 8 9]


(array([2, 5, 6, 7, 8, 9]), array([1, 0, 2, 4, 7, 9], dtype=int64))


[2 5 6 7 8 9]
[1 0 2 4 7 9]


